src/Entity/ModuleFormation.php
<?php

namespace App\Entity;

use App\Repository\ModuleFormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ModuleFormationRepository::class)
 */
class ModuleFormation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $libelle_module;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="moduleFormations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_categorie;

    /**
     * @ORM\OneToMany(targetEntity=Programme::class, mappedBy="module", orphanRemoval=true)
     */
    private $programmes;

    public function __construct()
    {
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelleModule(): ?string
    {
        return $this->libelle_module;
    }

    public function setLibelleModule(string $libelle_module): self
    {
        $this->libelle_module = $libelle_module;

        return $this;
    }

    public function getIdCategorie(): ?Categorie
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(?Categorie $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): self
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes[] = $programme;
            $programme->setModule($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): self
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getModule() === $this) {
                $programme->setModule(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->libelle_module;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 */
class Session
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $libelle_session;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="integer")
     */
    private $effectif;

    /**
     * @ORM\ManyToOne(targetEntity=Formation::class, inversedBy="sessions")
     */
    private $id_formation;

    /**
     * @ORM\OneToMany(targetEntity=Programme::class, mappedBy="session", orphanRemoval=true)
     */
    private $programmes;

    /**
     * @ORM\ManyToMany(targetEntity=Stagiaire::class, inversedBy="sessions")
     */
    private $stagiaires;

    /**
     * @ORM\ManyToOne(targetEntity=Formateur::class, inversedBy="sessions")
     */
    private $formateur;


    public function __construct()
    {
        $this->programmes = new ArrayCollection();
        $this->stagiaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelleSession(): ?string
    {
        return $this->libelle_session;
    }

    public function setLibelleSession(string $libelle_session): self
    {
        $this->libelle_session = $libelle_session;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getEffectif(): ?int
    {
        return $this->effectif;
    }

    public function setEffectif(int $effectif): self
    {
        $this->effectif = $effectif;

        return $this;
    }

    public function getIdFormation(): ?formation
    {
        return $this->id_formation;
    }

    public function setIdFormation(?formation $id_formation): self
    {
        $this->id_formation = $id_formation;

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): self
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes[] = $programme;
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): self
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): self
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires[] = $stagiaire;
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): self
    {
        $this->stagiaires->removeElement($stagiaire);

        return $this;
    }

    function __toString()
    {
        return $this->date_debut;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): self
    {
        $this->formateur = $formateur;

        return $this;
    }

    public function getPlaceReserve()
    {
        return count($this->getStagiaires());
    }

    public function getPlaceRestante()
    {
        return $this->getEffectif() - $this->getPlaceReserve();
    }

}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('LibelleSession', TextType::class)
            ->add('effectif', NumberType::class)
            ->add('dateDebut', DateType::class, [
                'widget' => 'single_text'

            ])
            ->add('dateFin', DateType::class, [
                'widget' => 'single_text'

            ])
            ->add('IdFormation', EntityType::class, [
                'class' => Formation::class,
                'choice_label' => 'intitule_formation'
            ])
            ->add('valider', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Programme;
use App\Entity\Stagiaire;
use App\Form\SessionType;
use App\Form\ProgrammeType;
use App\Repository\StagiaireRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bridge\Doctrine\ManagerRegistry as DoctrineManagerRegistry;

class SessionController extends AbstractController
{
    /**
     * @Route("/session", name="app_session")
     */
    public function index(ManagerRegistry $doctrine): Response
    {
        $sessions = $doctrine->getRepository(Session::class)->findAll();

        return $this->render('session/index.html.twig', [
            'sessions' => $sessions,
        ]);
    }

     /**
     * @Route("/session/add", name="add_session")
     * @Route("/session/update/{id}", name="update_session")
     */
    public function add(ManagerRegistry $doctrine, Session $session = null, Request  $request): Response
    {
        if(!$session) {
            $session = new Session();
        }

        $entityManager = $doctrine->getManager();
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $session = $form->getData();
            $entityManager->persist($session);
            $entityManager->flush();

            return $this->redirectToRoute('app_session');
        }

        return $this->render('session/add.html.twig', [
            'formSession' => $form->createView()

        ]);
    }

       
    /**
     * @Route("/session/addProgramme", name="add_programme")
     */
    public function addProgramme(ManagerRegistry $doctrine, Programme $programme = null, Request $request): Response
    {

        if (!$programme) {
            $programme = new Programme();
        }

        $entityManager = $doctrine->getManager();
        $form = $this->createForm(ProgrammeType::class, $programme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $programme = $form->getData();
            $entityManager->persist($programme);
            $entityManager->flush();

            return $this->redirectToRoute('app_session');
        }

        return $this->render('session/addProgramme.html.twig', [
            'formProgramme' => $form->createView()
        ]);
    }


    /**
     * @Route("/session/delete/{id}", name="delete_session")
     */
    public function delete(ManagerRegistry $doctrine, Session $session)
    {
        $entityManager = $doctrine->getManager();
        $entityManager->remove($session);
        $entityManager->flush();

        return $this->redirectToRoute("app_session");
    }


    /**
     * @Route("/session/{id}", name="show_session")
     */
    public function show(ManagerRegistry $doctrine, Session $session, StagiaireRepository $sta): Response
    {

        $nonInscrits = $sta->getNonInscrits($session->getId());

        return $this->render('session/show.html.twig', [
            'session' => $session,
            'nonInscrits' => $nonInscrits,
        ]);
    }

    /**
     * @Route("/session/inscrire/{idSession}/{idStagiaire}", name="programmer_session")
     * 
     * @ParamConverter("session", options={"mapping": {"idSession" : "id"}})
     * @ParamConverter("stagiaire", options={"mapping": {"idStagiaire" : "id"}})
     */
    public function programmer(ManagerRegistry $doctrine, Session $session, Stagiaire $stagiaire)
    {
        if ($session->getPlaceRestante() > 0){
            $session->addStagiaire($stagiaire);
            $doctrine->getManager()->flush();
            return $this->redirectToRoute('show_session', ['id'=>$session->getId()]);
        }
    }


    /**
     * @Route("/session/deleteStagiaire/{idSession}/{idStagiaire}", name="deprogrammer_session")
     * 
     * @ParamConverter("session", options={"mapping": {"idSession" : "id"}})
     * @ParamConverter("stagiaire", options={"mapping": {"idStagiaire" : "id"}})
     */
    public function deprogrammer(ManagerRegistry $doctrine, Session $session, Stagiaire $stagiaire)
    {
            $session->removeStagiaire($stagiaire);
            $doctrine->getManager()->flush();
            return $this->redirectToRoute('show_session', ['id'=>$session->getId()]);
        }

    /**
     * @Route("/session/deleteProgramme/{idSession}/{idProgramme}", name="delete_programme_session")
     *
     * @ParamConverter("session", options={"mapping" = {"idSession" : "id"}})
     * @ParamConverter("programme", options={"mapping" = {"idProgramme" : "id"}})
     */
    public function deleteProgramme(ManagerRegistry $doctrine, Programme $programme, Session $session)
    {
        $entityManager = $doctrine->getManager();
        $session->removeProgramme($programme);

        $entityManager->persist($session);
        $entityManager->flush();
        return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }
}

templates/session/add.html.twig
{% extends 'base.html.twig' %}

{% block title %} Ajout d'une session {% endblock %}

{% block body %}

<h1>Ajouter une session</h1>

{{form(formSession)}}

{% endblock %}

templates/session/addProgramme.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'un Module{% endblock %}

{% block body %}
    
    <div class="form-group">
    {{ form_start(formProgramme) }}
    {{ form_widget(formProgramme) }}
    {{ form_end(formProgramme) }}
    </div>

{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block Session %}{% endblock %}

{% block body %}

	<h1>Liste des Sessions
		<span class="badge bg-dark text-white">{{ sessions | length}}</span>
	</h1>


	<a href="{{ path('add_session')}}">
		<button type="button" class="btn btn-success">Ajouter une session</button>
	</a>

	<table class="table table-striped">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Session</th>
				<th scope="col">Edit</th>
				<th scope="col">Delete</th>
			</tr>
		</thead>
		<tbody>
			{% for session in sessions %}
				<tr>
					<td>
						<a href=" {{ path('show_session', {'id': session.id }) }} ">{{ session.LibelleSession }}</a>
					</td>
					<td>
						 <a href="{{ path('update_session', {'id' : session.id}) }}"><img src="/img/editer.png"></a>
					</td>
					<td>
						<a href="{{ path('delete_session', {'id' : session.id})}}"><img src="/img/trash-can.png"></a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<body>

		<div class="session-title">
			<h1>{{session.LibelleSession}}</h1>

			<h4>Places restantes :
				<span class="badge bg-dark text-white">{{ session.effectif - session.stagiaires | length }}</span>
			</h4>
		</div>

		<div class="main-session">
			<div class="card">
				<div class="card-header bg-dark text-white">
					<strong>
						Formateur Réferent :
						{{ session.formateur.Prenom }}
						{{  session.formateur.Nom  }}
					</strong>
				</div>
				<div class="card-body">
					<blockquote class="blockquote mb-0">
						<p>
							<strong>Date de début :</strong>
							{{ session.DateDebut | date('d/m/Y')}}</p>
						<p>
							<strong>Date de fin :</strong>
							{{ session.DateFin | date('d/m/Y')}}</p>
						<p>
							<strong>Nombre de stagiaire :</strong>
							{{ session.Effectif }}</p>
					</blockquote>
				</div>
			</div>

<a href="{{ path('add_programme')}}">
		<button type="button" class="btn btn-success">Ajouter une session</button>
	</a>
			<table class="table table-striped">
				<thead class="thead-dark">
					<tr>
						<th scope="col">Module</th>
						<th scope="col">Catégorie</th>
						<th scope="col">Durée</th>
						<th scope="col">Retirer</th>
					</tr>
				</thead>
				<tbody>
					{% for programme in session.programmes %}
						<tr>
							<td>{{ programme.module }}</td>
							<td>{{ programme.module.idCategorie }}</td>
							<td>{{ programme.duree }}</td>
							<td><a href="{{ path('delete_programme_session', {'idSession' : session.id , 'idProgramme' : programme.id})}}"><img src="/img/logout.png"></a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

			<div class="stagiaire-session">
				{% if session.stagiaires | length > 0 %}

					<table class="table table-striped">
						<thead class="thead-dark">
							<tr>
								<th scope="col">Stagiaire(s) Inscrits :
									<span class="badge bg-white text-dark">{{ session.stagiaires | length }}</span>
								</th>
								<th>Déprogrammer</th>
							</tr>
						</thead>
						<tbody>
							{% for stagiaire in session.stagiaires %}
								<tr>
									<td>
										<a href=" {{ path('show_stagiaire', {'id': stagiaire.id }) }} ">{{ stagiaire.Nom }}
											{{  stagiaire.Prenom  }}</a>
									</td>
									<td><a href="{{ path("deprogrammer_session",{'idSession': session.id, 'idStagiaire': stagiaire.id}) }}"><img src="/img/logout.png"></a></td>

								</tr>
							{% endfor %}
						</tbody>
					</table>
				{% endif %}

				<table class="table table-striped non-inscrits">
					<thead class="thead-dark">
						<tr>
							<th scope="col">Stagiaire(s) non inscrits :
								<span class="badge bg-white text-dark">{{ nonInscrits | length }}</span>
							</th>
							<th>Inscrire</th>
						</tr>
					</thead>
					<tbody>
						{% for stagiaire in nonInscrits %}
							<tr>
								<td>
									<a href="#">{{ stagiaire.Nom }}
										{{ stagiaire.Prenom}}</>
								</td>
								<td><a href="{{ path("programmer_session",{'idSession': session.id, 'idStagiaire': stagiaire.id}) }}"><img src="/img/sign-up.png"></a></td>
								</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</body>
{% endblock %}